# This is a basic workflow to help you get started with Actions

name: Python Linter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
      with:
        # A list of all paths to test
        python-root-list: . # optional, default is .
        # Use Pylint
        use-pylint: true # optional, default is true
        # Use pycodestyle
        use-pycodestyle: true # optional, default is true
        # Use Flake8
        use-flake8: true # optional, default is true
        # Use Black
        use-black: true # optional, default is true
        # Use mypy
        use-mypy: false # optional, default is true
        # Use isort
        use-isort: false# optional, default is true
        # Extra options: pylint $(extra-pylint-options) $(python-root-list)

